In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

C:\Users\aksha\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
training_dataset=pd.read_csv('train.csv')
training_dataset

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [3]:
testing_dataset=pd.read_csv('test.csv')
testing_dataset

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN  MnPrv   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            HLS    AllPub  ...         144        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1454         Lvl    AllPub  ...           0        0    NaN    NaN   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN    NaN   
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      6    2010        WD         Normal  
1           Gar2   12500      6    2010        WD         Normal  
2            NaN       0      3    2010        WD         Normal  
3            NaN       0      6    2010        WD         Normal  
4            NaN       0      1    2010        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1454         NaN       0      6    2006        WD         Normal  
1455         NaN       0      4    2006        WD        Abnorml  
1456         NaN       0      9    2006        WD        Abnorml  
1457        Shed     700      7    2006        WD         Normal  
1458         NaN       0     11    2006        WD         Normal  

[1459 rows x 80 columns]

In [4]:
cols=np.array(training_dataset.columns)
len(cols)

81

In [5]:
training_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

# PRE-PROCESSING CATEGORICAL DATA

In [6]:
training_dataset.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [7]:
training_dataset.shape

(1460, 81)

In [8]:
training_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [9]:
a=training_dataset.dtypes==object
obj=a[a==True].index
obj=np.array(obj)
obj

array(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood',
       'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish',
       'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence',
       'MiscFeature', 'SaleType', 'SaleCondition'], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [11]:
for i in obj:
    training_dataset[i]=label.fit_transform(training_dataset[i])
    testing_dataset[i]=label.fit_transform(testing_dataset[i])


In [12]:
training_dataset

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0        1          60         3         65.0     8450       1      2   
1        2          20         3         80.0     9600       1      2   
2        3          60         3         68.0    11250       1      2   
3        4          70         3         60.0     9550       1      2   
4        5          60         3         84.0    14260       1      2   
...    ...         ...       ...          ...      ...     ...    ...   
1455  1456          60         3         62.0     7917       1      2   
1456  1457          20         3         85.0    13175       1      2   
1457  1458          70         3         66.0     9042       1      2   
1458  1459          20         3         68.0     9717       1      2   
1459  1460          20         3         75.0     9937       1      2   

      LotShape  LandContour  Utilities  ...  PoolArea  PoolQC  Fence  \
0            3            3          0  ...         0       3      4   
1            3            3          0  ...         0       3      4   
2            0            3          0  ...         0       3      4   
3            0            3          0  ...         0       3      4   
4            0            3          0  ...         0       3      4   
...        ...          ...        ...  ...       ...     ...    ...   
1455         3            3          0  ...         0       3      4   
1456         3            3          0  ...         0       3      2   
1457         3            3          0  ...         0       3      0   
1458         3            3          0  ...         0       3      4   
1459         3            3          0  ...         0       3      4   

      MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0               4        0       2    2008         8              4     208500  
1               4        0       5    2007         8              4     181500  
2               4        0       9    2008         8              4     223500  
3               4        0       2    2006         8              0     140000  
4               4        0      12    2008         8              4     250000  
...           ...      ...     ...     ...       ...            ...        ...  
1455            4        0       8    2007         8              4     175000  
1456            4        0       2    2010         8              4     210000  
1457            2     2500       5    2010         8              4     266500  
1458            4        0       4    2010         8              4     142125  
1459            4        0       6    2008         8              4     147500  

[1460 rows x 81 columns]

In [13]:
testing_dataset

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0     1461          20         2         80.0    11622       1      2   
1     1462          20         3         81.0    14267       1      2   
2     1463          60         3         74.0    13830       1      2   
3     1464          60         3         78.0     9978       1      2   
4     1465         120         3         43.0     5005       1      2   
...    ...         ...       ...          ...      ...     ...    ...   
1454  2915         160         4         21.0     1936       1      2   
1455  2916         160         4         21.0     1894       1      2   
1456  2917          20         3        160.0    20000       1      2   
1457  2918          85         3         62.0    10441       1      2   
1458  2919          60         3         74.0     9627       1      2   

      LotShape  LandContour  Utilities  ...  ScreenPorch  PoolArea  PoolQC  \
0            3            3          0  ...          120         0       2   
1            0            3          0  ...            0         0       2   
2            0            3          0  ...            0         0       2   
3            0            3          0  ...            0         0       2   
4            0            1          0  ...          144         0       2   
...        ...          ...        ...  ...          ...       ...     ...   
1454         3            3          0  ...            0         0       2   
1455         3            3          0  ...            0         0       2   
1456         3            3          0  ...            0         0       2   
1457         3            3          0  ...            0         0       2   
1458         3            3          0  ...            0         0       2   

      Fence  MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  
0         2            3        0       6    2010         8              4  
1         4            0    12500       6    2010         8              4  
2         2            3        0       3    2010         8              4  
3         4            3        0       6    2010         8              4  
4         4            3        0       1    2010         8              4  
...     ...          ...      ...     ...     ...       ...            ...  
1454      4            3        0       6    2006         8              4  
1455      4            3        0       4    2006         8              0  
1456      4            3        0       9    2006         8              0  
1457      2            2      700       7    2006         8              4  
1458      4            3        0      11    2006         8              4  

[1459 rows x 80 columns]

In [14]:
a=training_dataset.dtypes==object
obj=a[a==True].index
obj

Index([], dtype='object')

## DATA CLEANING

In [15]:
type(training_dataset[training_dataset.notnull()].count())

pandas.core.series.Series

In [16]:
check=training_dataset[training_dataset.notnull()].count()
check[check<1460]

LotFrontage    1201
MasVnrArea     1452
GarageYrBlt    1379
dtype: int64

In [17]:
training_dataset.LotFrontage.unique()

array([ 65.,  80.,  68.,  60.,  84.,  85.,  75.,  nan,  51.,  50.,  70.,
        91.,  72.,  66., 101.,  57.,  44., 110.,  98.,  47., 108., 112.,
        74., 115.,  61.,  48.,  33.,  52., 100.,  24.,  89.,  63.,  76.,
        81.,  95.,  69.,  21.,  32.,  78., 121., 122.,  40., 105.,  73.,
        77.,  64.,  94.,  34.,  90.,  55.,  88.,  82.,  71., 120., 107.,
        92., 134.,  62.,  86., 141.,  97.,  54.,  41.,  79., 174.,  99.,
        67.,  83.,  43., 103.,  93.,  30., 129., 140.,  35.,  37., 118.,
        87., 116., 150., 111.,  49.,  96.,  59.,  36.,  56., 102.,  58.,
        38., 109., 130.,  53., 137.,  45., 106., 104.,  42.,  39., 144.,
       114., 128., 149., 313., 168., 182., 138., 160., 152., 124., 153.,
        46.])

In [18]:
mean_lot_frontage=training_dataset.LotFrontage.mean()
training_dataset.LotFrontage.fillna(mean_lot_frontage,inplace=True)

In [19]:
check=training_dataset[training_dataset.notnull()].count()
check[check<1460]

MasVnrArea     1452
GarageYrBlt    1379
dtype: int64

In [20]:
training_dataset.drop(['Alley','FireplaceQu','PoolQC','Fence','MiscFeature'],inplace=True,axis=1)
training_dataset

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0        1          60         3         65.0     8450       1         3   
1        2          20         3         80.0     9600       1         3   
2        3          60         3         68.0    11250       1         0   
3        4          70         3         60.0     9550       1         0   
4        5          60         3         84.0    14260       1         0   
...    ...         ...       ...          ...      ...     ...       ...   
1455  1456          60         3         62.0     7917       1         3   
1456  1457          20         3         85.0    13175       1         3   
1457  1458          70         3         66.0     9042       1         3   
1458  1459          20         3         68.0     9717       1         3   
1459  1460          20         3         75.0     9937       1         3   

      LandContour  Utilities  LotConfig  ...  EnclosedPorch  3SsnPorch  \
0               3          0          4  ...              0          0   
1               3          0          2  ...              0          0   
2               3          0          4  ...              0          0   
3               3          0          0  ...            272          0   
4               3          0          2  ...              0          0   
...           ...        ...        ...  ...            ...        ...   
1455            3          0          4  ...              0          0   
1456            3          0          4  ...              0          0   
1457            3          0          4  ...              0          0   
1458            3          0          4  ...            112          0   
1459            3          0          4  ...              0          0   

      ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  SaleCondition  \
0               0         0        0       2    2008         8              4   
1               0         0        0       5    2007         8              4   
2               0         0        0       9    2008         8              4   
3               0         0        0       2    2006         8              0   
4               0         0        0      12    2008         8              4   
...           ...       ...      ...     ...     ...       ...            ...   
1455            0         0        0       8    2007         8              4   
1456            0         0        0       2    2010         8              4   
1457            0         0     2500       5    2010         8              4   
1458            0         0        0       4    2010         8              4   
1459            0         0        0       6    2008         8              4   

      SalePrice  
0        208500  
1        181500  
2        223500  
3        140000  
4        250000  
...         ...  
1455     175000  
1456     210000  
1457     266500  
1458     142125  
1459     147500  

[1460 rows x 76 columns]

In [21]:
check=training_dataset[training_dataset.notnull()].count()
check[check<1460]

MasVnrArea     1452
GarageYrBlt    1379
dtype: int64

In [22]:
training_dataset.MasVnrArea.unique()

array([1.960e+02, 0.000e+00, 1.620e+02, 3.500e+02, 1.860e+02, 2.400e+02,
       2.860e+02, 3.060e+02, 2.120e+02, 1.800e+02, 3.800e+02, 2.810e+02,
       6.400e+02, 2.000e+02, 2.460e+02, 1.320e+02, 6.500e+02, 1.010e+02,
       4.120e+02, 2.720e+02, 4.560e+02, 1.031e+03, 1.780e+02, 5.730e+02,
       3.440e+02, 2.870e+02, 1.670e+02, 1.115e+03, 4.000e+01, 1.040e+02,
       5.760e+02, 4.430e+02, 4.680e+02, 6.600e+01, 2.200e+01, 2.840e+02,
       7.600e+01, 2.030e+02, 6.800e+01, 1.830e+02, 4.800e+01, 2.800e+01,
       3.360e+02, 6.000e+02, 7.680e+02, 4.800e+02, 2.200e+02, 1.840e+02,
       1.129e+03, 1.160e+02, 1.350e+02, 2.660e+02, 8.500e+01, 3.090e+02,
       1.360e+02, 2.880e+02, 7.000e+01, 3.200e+02, 5.000e+01, 1.200e+02,
       4.360e+02, 2.520e+02, 8.400e+01, 6.640e+02, 2.260e+02, 3.000e+02,
       6.530e+02, 1.120e+02, 4.910e+02, 2.680e+02, 7.480e+02, 9.800e+01,
       2.750e+02, 1.380e+02, 2.050e+02, 2.620e+02, 1.280e+02, 2.600e+02,
       1.530e+02, 6.400e+01, 3.120e+02, 1.600e+01, 

In [23]:
mean_mas_vnr_area=training_dataset.MasVnrArea.mean()
training_dataset.MasVnrArea.fillna(mean_mas_vnr_area,inplace=True)

In [24]:
check=training_dataset[training_dataset.notnull()].count()
check[check<1460]

GarageYrBlt    1379
dtype: int64

In [25]:
training_dataset.dropna(axis=1,inplace=True)
training_dataset

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0        1          60         3         65.0     8450       1         3   
1        2          20         3         80.0     9600       1         3   
2        3          60         3         68.0    11250       1         0   
3        4          70         3         60.0     9550       1         0   
4        5          60         3         84.0    14260       1         0   
...    ...         ...       ...          ...      ...     ...       ...   
1455  1456          60         3         62.0     7917       1         3   
1456  1457          20         3         85.0    13175       1         3   
1457  1458          70         3         66.0     9042       1         3   
1458  1459          20         3         68.0     9717       1         3   
1459  1460          20         3         75.0     9937       1         3   

      LandContour  Utilities  LotConfig  ...  EnclosedPorch  3SsnPorch  \
0               3          0          4  ...              0          0   
1               3          0          2  ...              0          0   
2               3          0          4  ...              0          0   
3               3          0          0  ...            272          0   
4               3          0          2  ...              0          0   
...           ...        ...        ...  ...            ...        ...   
1455            3          0          4  ...              0          0   
1456            3          0          4  ...              0          0   
1457            3          0          4  ...              0          0   
1458            3          0          4  ...            112          0   
1459            3          0          4  ...              0          0   

      ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  SaleCondition  \
0               0         0        0       2    2008         8              4   
1               0         0        0       5    2007         8              4   
2               0         0        0       9    2008         8              4   
3               0         0        0       2    2006         8              0   
4               0         0        0      12    2008         8              4   
...           ...       ...      ...     ...     ...       ...            ...   
1455            0         0        0       8    2007         8              4   
1456            0         0        0       2    2010         8              4   
1457            0         0     2500       5    2010         8              4   
1458            0         0        0       4    2010         8              4   
1459            0         0        0       6    2008         8              4   

      SalePrice  
0        208500  
1        181500  
2        223500  
3        140000  
4        250000  
...         ...  
1455     175000  
1456     210000  
1457     266500  
1458     142125  
1459     147500  

[1460 rows x 75 columns]

In [26]:
check=training_dataset[training_dataset.notnull()].count()
check[check<1460]

Series([], dtype: int64)

## DATA CLEANING FOR TEST DATASET

In [27]:
testing_dataset.shape

(1459, 80)

In [28]:
check1=testing_dataset[testing_dataset.notnull()].count()
check1[check1<1459]

LotFrontage     1232
MasVnrArea      1444
BsmtFinSF1      1458
BsmtFinSF2      1458
BsmtUnfSF       1458
TotalBsmtSF     1458
BsmtFullBath    1457
BsmtHalfBath    1457
GarageYrBlt     1381
GarageCars      1458
GarageArea      1458
dtype: int64

In [29]:
testing_dataset.drop(['Alley','FireplaceQu','PoolQC','Fence','MiscFeature','GarageYrBlt'],inplace=True,axis=1)
testing_dataset

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0     1461          20         2         80.0    11622       1         3   
1     1462          20         3         81.0    14267       1         0   
2     1463          60         3         74.0    13830       1         0   
3     1464          60         3         78.0     9978       1         0   
4     1465         120         3         43.0     5005       1         0   
...    ...         ...       ...          ...      ...     ...       ...   
1454  2915         160         4         21.0     1936       1         3   
1455  2916         160         4         21.0     1894       1         3   
1456  2917          20         3        160.0    20000       1         3   
1457  2918          85         3         62.0    10441       1         3   
1458  2919          60         3         74.0     9627       1         3   

      LandContour  Utilities  LotConfig  ...  OpenPorchSF  EnclosedPorch  \
0               3          0          4  ...            0              0   
1               3          0          0  ...           36              0   
2               3          0          4  ...           34              0   
3               3          0          4  ...           36              0   
4               1          0          4  ...           82              0   
...           ...        ...        ...  ...          ...            ...   
1454            3          0          4  ...            0              0   
1455            3          0          4  ...           24              0   
1456            3          0          4  ...            0              0   
1457            3          0          4  ...           32              0   
1458            3          0          4  ...           48              0   

      3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  \
0             0          120         0        0       6    2010         8   
1             0            0         0    12500       6    2010         8   
2             0            0         0        0       3    2010         8   
3             0            0         0        0       6    2010         8   
4             0          144         0        0       1    2010         8   
...         ...          ...       ...      ...     ...     ...       ...   
1454          0            0         0        0       6    2006         8   
1455          0            0         0        0       4    2006         8   
1456          0            0         0        0       9    2006         8   
1457          0            0         0      700       7    2006         8   
1458          0            0         0        0      11    2006         8   

      SaleCondition  
0                 4  
1                 4  
2                 4  
3                 4  
4                 4  
...             ...  
1454              4  
1455              0  
1456              0  
1457              4  
1458              4  

[1459 rows x 74 columns]

In [30]:
check1=testing_dataset[testing_dataset.notnull()].count()
check1[check1<1459]

LotFrontage     1232
MasVnrArea      1444
BsmtFinSF1      1458
BsmtFinSF2      1458
BsmtUnfSF       1458
TotalBsmtSF     1458
BsmtFullBath    1457
BsmtHalfBath    1457
GarageCars      1458
GarageArea      1458
dtype: int64

In [31]:
mean_lot_frontage1=testing_dataset.LotFrontage.mean()
testing_dataset.LotFrontage.fillna(mean_lot_frontage1,inplace=True)

In [32]:
check1=testing_dataset[testing_dataset.notnull()].count()
check1[check1<1459]

MasVnrArea      1444
BsmtFinSF1      1458
BsmtFinSF2      1458
BsmtUnfSF       1458
TotalBsmtSF     1458
BsmtFullBath    1457
BsmtHalfBath    1457
GarageCars      1458
GarageArea      1458
dtype: int64

In [33]:
testing_dataset.fillna(100,inplace=True)

In [34]:
check1=testing_dataset[testing_dataset.notnull()].count()
check1[check1<1459]

Series([], dtype: int64)

In [35]:
testing_dataset.shape

(1459, 74)

In [36]:
X_train_df=training_dataset.drop('SalePrice',axis=1)
X_train_df

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0        1          60         3         65.0     8450       1         3   
1        2          20         3         80.0     9600       1         3   
2        3          60         3         68.0    11250       1         0   
3        4          70         3         60.0     9550       1         0   
4        5          60         3         84.0    14260       1         0   
...    ...         ...       ...          ...      ...     ...       ...   
1455  1456          60         3         62.0     7917       1         3   
1456  1457          20         3         85.0    13175       1         3   
1457  1458          70         3         66.0     9042       1         3   
1458  1459          20         3         68.0     9717       1         3   
1459  1460          20         3         75.0     9937       1         3   

      LandContour  Utilities  LotConfig  ...  OpenPorchSF  EnclosedPorch  \
0               3          0          4  ...           61              0   
1               3          0          2  ...            0              0   
2               3          0          4  ...           42              0   
3               3          0          0  ...           35            272   
4               3          0          2  ...           84              0   
...           ...        ...        ...  ...          ...            ...   
1455            3          0          4  ...           40              0   
1456            3          0          4  ...            0              0   
1457            3          0          4  ...           60              0   
1458            3          0          4  ...            0            112   
1459            3          0          4  ...           68              0   

      3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  \
0             0            0         0        0       2    2008         8   
1             0            0         0        0       5    2007         8   
2             0            0         0        0       9    2008         8   
3             0            0         0        0       2    2006         8   
4             0            0         0        0      12    2008         8   
...         ...          ...       ...      ...     ...     ...       ...   
1455          0            0         0        0       8    2007         8   
1456          0            0         0        0       2    2010         8   
1457          0            0         0     2500       5    2010         8   
1458          0            0         0        0       4    2010         8   
1459          0            0         0        0       6    2008         8   

      SaleCondition  
0                 4  
1                 4  
2                 4  
3                 0  
4                 4  
...             ...  
1455              4  
1456              4  
1457              4  
1458              4  
1459              4  

[1460 rows x 74 columns]

In [37]:
X_test_df=testing_dataset
X_test_df

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0     1461          20         2         80.0    11622       1         3   
1     1462          20         3         81.0    14267       1         0   
2     1463          60         3         74.0    13830       1         0   
3     1464          60         3         78.0     9978       1         0   
4     1465         120         3         43.0     5005       1         0   
...    ...         ...       ...          ...      ...     ...       ...   
1454  2915         160         4         21.0     1936       1         3   
1455  2916         160         4         21.0     1894       1         3   
1456  2917          20         3        160.0    20000       1         3   
1457  2918          85         3         62.0    10441       1         3   
1458  2919          60         3         74.0     9627       1         3   

      LandContour  Utilities  LotConfig  ...  OpenPorchSF  EnclosedPorch  \
0               3          0          4  ...            0              0   
1               3          0          0  ...           36              0   
2               3          0          4  ...           34              0   
3               3          0          4  ...           36              0   
4               1          0          4  ...           82              0   
...           ...        ...        ...  ...          ...            ...   
1454            3          0          4  ...            0              0   
1455            3          0          4  ...           24              0   
1456            3          0          4  ...            0              0   
1457            3          0          4  ...           32              0   
1458            3          0          4  ...           48              0   

      3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  \
0             0          120         0        0       6    2010         8   
1             0            0         0    12500       6    2010         8   
2             0            0         0        0       3    2010         8   
3             0            0         0        0       6    2010         8   
4             0          144         0        0       1    2010         8   
...         ...          ...       ...      ...     ...     ...       ...   
1454          0            0         0        0       6    2006         8   
1455          0            0         0        0       4    2006         8   
1456          0            0         0        0       9    2006         8   
1457          0            0         0      700       7    2006         8   
1458          0            0         0        0      11    2006         8   

      SaleCondition  
0                 4  
1                 4  
2                 4  
3                 4  
4                 4  
...             ...  
1454              4  
1455              0  
1456              0  
1457              4  
1458              4  

[1459 rows x 74 columns]

# FEATURE ENGINEERING

In [38]:
#MUTUAL INFORMATION
from sklearn.feature_selection import mutual_info_regression
mi_scores=mutual_info_regression(X_train_df,training_dataset.SalePrice)
mi_scores=pd.Series(mi_scores,index=X_train_df.columns)
select=mi_scores.sort_values(ascending=False)
selected=select[select>0.1]
selected

OverallQual     0.552960
Neighborhood    0.510746
GrLivArea       0.482246
GarageCars      0.373188
TotalBsmtSF     0.367139
GarageArea      0.364098
YearBuilt       0.361960
BsmtQual        0.333288
ExterQual       0.322693
KitchenQual     0.315529
1stFlrSF        0.309082
MSSubClass      0.275510
GarageFinish    0.256956
FullBath        0.254997
YearRemodAdd    0.242908
TotRmsAbvGrd    0.222684
Foundation      0.213389
GarageType      0.208571
2ndFlrSF        0.204547
LotFrontage     0.196659
HeatingQC       0.170077
Exterior2nd     0.168556
Fireplaces      0.161302
LotArea         0.157887
BsmtFinType1    0.152362
BsmtFinSF1      0.149458
OpenPorchSF     0.142152
Exterior1st     0.127990
MasVnrType      0.122304
BsmtUnfSF       0.121216
MSZoning        0.120854
WoodDeckSF      0.110918
OverallCond     0.110006
MasVnrArea      0.105865
dtype: float64

In [39]:
selected.index

Index(['OverallQual', 'Neighborhood', 'GrLivArea', 'GarageCars', 'TotalBsmtSF',
       'GarageArea', 'YearBuilt', 'BsmtQual', 'ExterQual', 'KitchenQual',
       '1stFlrSF', 'MSSubClass', 'GarageFinish', 'FullBath', 'YearRemodAdd',
       'TotRmsAbvGrd', 'Foundation', 'GarageType', '2ndFlrSF', 'LotFrontage',
       'HeatingQC', 'Exterior2nd', 'Fireplaces', 'LotArea', 'BsmtFinType1',
       'BsmtFinSF1', 'OpenPorchSF', 'Exterior1st', 'MasVnrType', 'BsmtUnfSF',
       'MSZoning', 'WoodDeckSF', 'OverallCond', 'MasVnrArea'],
      dtype='object')

# MAKING TRAIN,TEST DATSETS

In [40]:
X_test=np.array(X_test_df.values)
X_test

array([[1.461e+03, 2.000e+01, 2.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.462e+03, 2.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.463e+03, 6.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       ...,
       [2.917e+03, 2.000e+01, 3.000e+00, ..., 2.006e+03, 8.000e+00,
        0.000e+00],
       [2.918e+03, 8.500e+01, 3.000e+00, ..., 2.006e+03, 8.000e+00,
        4.000e+00],
       [2.919e+03, 6.000e+01, 3.000e+00, ..., 2.006e+03, 8.000e+00,
        4.000e+00]])

In [41]:
X_train=np.array(X_train_df.values)
X_train

array([[1.000e+00, 6.000e+01, 3.000e+00, ..., 2.008e+03, 8.000e+00,
        4.000e+00],
       [2.000e+00, 2.000e+01, 3.000e+00, ..., 2.007e+03, 8.000e+00,
        4.000e+00],
       [3.000e+00, 6.000e+01, 3.000e+00, ..., 2.008e+03, 8.000e+00,
        4.000e+00],
       ...,
       [1.458e+03, 7.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.459e+03, 2.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.460e+03, 2.000e+01, 3.000e+00, ..., 2.008e+03, 8.000e+00,
        4.000e+00]])

In [42]:
y_train=np.array(training_dataset.SalePrice)
y_train

array([208500, 181500, 223500, ..., 266500, 142125, 147500], dtype=int64)

In [43]:
y_test=np.array(pd.read_csv('sample_submission.csv')['SalePrice'])
y_test


array([169277.0524984 , 187758.39398877, 183583.68356955, ...,
       219222.42340006, 184924.279659  , 187741.86665748])

# FITTING LASSO REGRESSION MODEL

In [44]:
from sklearn.linear_model import Lasso
l=Lasso(alpha=1000000)
l.fit(X_train,y_train)

Lasso(alpha=1000000)

In [45]:
y_predict=l.predict(X_test)
y_predict

array([149491.05360327, 173960.87729813, 186686.19562337, ...,
       184977.79677779,  99077.02505467, 227840.6073084 ])

In [46]:
print("Score of training dataset using lasso regression:",l.score(X_train,y_train))
print("Score of testing dataset using lasso regression:",l.score(X_test,y_test))

Score of training dataset using lasso regression: 0.6725379165480788
Score of testing dataset using lasso regression: -9.69286267910297


In [47]:
print("No:of features used:",l.coef_)

No:of features used: [-0.         -0.         -0.         -0.          0.24582478  0.
 -0.          0.         -0.          0.          0.          0.
  0.         -0.         -0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.         24.32253105 -0.          0.          0.         -0.
  0.         -0.         -0.         12.28576847  0.         -0.
  0.         39.6293952  -0.         -0.          0.          0.
  0.          0.         -0.         67.45195754  0.         -0.
  0.          0.         -0.         -0.         -0.          0.
  0.          0.         -0.         -0.          0.         74.92411032
  0.          0.          0.          0.          0.         -0.
  0.          0.         -0.         -0.          0.         -0.
  0.          0.        ]


In [48]:
from sklearn.metrics import mean_squared_error
MSR=mean_squared_error(y_test,y_predict)
print("Mean squared error of decision trees:",MSR)

Mean squared error of decision trees: 2915594221.150696


In [49]:
predict_file1=pd.DataFrame({'Id':np.array(X_test_df['Id']),'SalePrice':y_predict})
predict_file1.head(10)

Id      SalePrice
0  1461  149491.053603
1  1462  173960.877298
2  1463  186686.195623
3  1464  181239.071916
4  1465  170236.898803
5  1466  168094.731928
6  1467  162069.266122
7  1468  152394.963094
8  1469  181010.093439
9  1470  136523.254363

In [50]:
predict_file1.to_csv('predict1.csv',index=False)

# DECISION TREES

In [51]:
from sklearn.tree import DecisionTreeRegressor
tree=DecisionTreeRegressor(max_depth=3)
tree.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=3)

In [52]:
y_predict1=tree.predict(X_test)
y_predict1

array([124907.77836879, 124907.77836879, 165466.08908046, ...,
       124907.77836879, 124907.77836879, 247980.9875    ])

In [53]:
print("Score of training dataset using decision trees:",tree.score(X_train,y_train))
print("Score of test dataset using decision trees:",tree.score(X_test,y_test))

Score of training dataset using decision trees: 0.7444959181556796
Score of test dataset using decision trees: -15.388551123591434


In [54]:
from sklearn.metrics import mean_squared_error
MSR=mean_squared_error(y_test,y_predict1)
print("Mean squared error of decision trees:",MSR)

Mean squared error of decision trees: 4468622330.889638


In [55]:
predict_file2=pd.DataFrame({'Id':np.array(X_test_df['Id']),'SalePrice':y_predict1})
predict_file2.head(10)

Id      SalePrice
0  1461  124907.778369
1  1462  124907.778369
2  1463  165466.089080
3  1464  165466.089080
4  1465  249392.466019
5  1466  165466.089080
6  1467  124907.778369
7  1468  165466.089080
8  1469  194238.744770
9  1470  124907.778369

In [56]:
predict_file2.to_csv('predict2.csv',index=False)

# LINEAR REGRESSION

In [57]:
from sklearn.linear_model import LinearRegression
linear_reg=LinearRegression()
linear_reg.fit(X_train,y_train)

LinearRegression()

In [58]:
y_predict2=linear_reg.predict(X_test)
y_predict2

array([102010.07623079, 150020.18201101, 165373.35427985, ...,
       144684.29124764, 115985.904009  , 239528.42890907])

In [59]:
print("Score of training dataset using linear regression:",linear_reg.score(X_train,y_train))
print("Score of test dataset using linear regression:",linear_reg.score(X_test,y_test))

Score of training dataset using linear regression: 0.8498439182487711
Score of test dataset using linear regression: -23.886535261309298


In [60]:
from sklearn.metrics import mean_squared_error
MSR=mean_squared_error(y_test,y_predict2)
print("Mean squared error of linear regression:",MSR)

Mean squared error of linear regression: 6785744900.11345


In [61]:
predict_file4=pd.DataFrame({'Id':np.array(X_test_df['Id']),'SalePrice':y_predict2})
predict_file4.head(10)

Id      SalePrice
0  1461  102010.076231
1  1462  150020.182011
2  1463  165373.354280
3  1464  180239.156574
4  1465  184208.292406
5  1466  169356.420999
6  1467  183557.287122
7  1468  157859.918438
8  1469  196983.130833
9  1470  105246.661609

In [62]:
predict_file4.to_csv('predict4.csv',index=False)

# KNN

In [63]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=50)
knn.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=50)

In [64]:
y_predict3=knn.predict(X_test)
y_predict3

array([146634.7 , 202659.62, 192943.12, ..., 213374.46, 136172.2 ,
       190208.  ])

In [65]:
print("Score of training dataset using knn regression:",knn.score(X_train,y_train))
print("Score of test dataset using knn regression:",knn.score(X_test,y_test))

Score of training dataset using knn regression: 0.5726311207795018
Score of test dataset using knn regression: -3.487490820129022


In [66]:
from sklearn.metrics import mean_squared_error
MSR=mean_squared_error(y_test,y_predict3)
print("Mean squared error of KNN regression:",MSR)

Mean squared error of KNN regression: 1223592100.1963687


In [67]:
predict_file3=pd.DataFrame({'Id':np.array(X_test_df['Id']),'SalePrice':y_predict3})
predict_file3.head(10)

Id  SalePrice
0  1461  146634.70
1  1462  202659.62
2  1463  192943.12
3  1464  178271.80
4  1465  144950.30
5  1466  173780.50
6  1467  149076.12
7  1468  155054.96
8  1469  151733.80
9  1470  137155.12

In [68]:
predict_file3.to_csv('predict3.csv',index=False)

# USING RANDOM FOREST

In [69]:
from sklearn.ensemble import RandomForestRegressor
forest=RandomForestRegressor(max_depth=3)
forest.fit(X_train,y_train)

RandomForestRegressor(max_depth=3)

In [70]:
y_predict5=forest.predict(X_test)
y_predict5

array([122511.222922  , 138758.3337378 , 163456.14099897, ...,
       135116.82215484, 122903.42521432, 231155.11906655])

In [71]:
print("Score of training dataset using random forests:",forest.score(X_train,y_train))
print("Score of test dataset using random forests:",forest.score(X_test,y_test))

Score of training dataset using random forests: 0.7976296990478908
Score of test dataset using random forests: -13.48418951930437


In [72]:
from sklearn.metrics import mean_squared_error
MSR=mean_squared_error(y_test,y_predict5)
print("Mean squared error of random forest regression:",MSR)

Mean squared error of KNN regression: 3949365153.923215


In [73]:
predict_file5=pd.DataFrame({'Id':np.array(X_test_df['Id']),'SalePrice':y_predict5})
predict_file5.head(10)

Id      SalePrice
0  1461  122511.222922
1  1462  138758.333738
2  1463  163456.140999
3  1464  170358.455251
4  1465  249324.498403
5  1466  168507.208983
6  1467  139414.749749
7  1468  166003.911128
8  1469  183894.774888
9  1470  123630.883138

In [74]:
predict_file5.to_csv('predict5.csv',index=False)

# USING XGB

In [100]:
from xgboost import XGBRegressor
xgb=XGBRegressor()
xgb.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [101]:
y_predict6=xgb.predict(X_test)
y_predict6

array([116803.41, 153947.78, 173412.31, ..., 165130.52, 120225.1 ,
       201810.86], dtype=float32)

In [102]:
print("Score of training dataset using XGB:",xgb.score(X_train,y_train))
print("Score of test dataset using XGB :",xgb.score(X_test,y_test))

Score of training dataset using XGB: 0.9995584363196127
Score of test dataset using XGB : -18.888080864234002


In [103]:
from sklearn.metrics import mean_squared_error
MSR=mean_squared_error(y_test,y_predict6)
print("Mean squared error of XGB:",MSR)

Mean squared error of XGB: 5422829730.232993
